"""etfhextractor_demo_bars

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 15:35:01.830265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etfhextractor_markets__demobarsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset__mainsequence_examples.unique_identifier'], name=op.f('fk__etfhextractor_markets__demobarsts__mainsequence_ae05555751'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'etfhextractor_markets', 'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.DemoBarsTS'}
    )
    op.create_index('uix__etfhextractor_markets__demobarsts__mainsequence_d1b8a41dd8', 'etfhextractor_markets__demobarsts__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__etfhextractor_markets__demobarsts__mainsequence_d1b8a41dd8', table_name='etfhextractor_markets__demobarsts__mainsequence_examples')
    op.drop_table('etfhextractor_markets__demobarsts__mainsequence_examples')
    # ### end Alembic commands ###
