"""etfhextractor_demo_bars

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 19:34:56.408920

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etfhextractor_markets__demobarsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__etfhextractor_markets__demobarsts__asset_identif_aa195e0879'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'etfhextractor_markets', 'namespace': 'etfhextractor', 'identifier': 'etfhextractor.DemoBarsTS'}
    )
    op.create_index('uix__etfhextractor_markets__demobarsts__time_index_6c1d0165ee', 'etfhextractor_markets__demobarsts', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__etfhextractor_markets__demobarsts__time_index_6c1d0165ee', table_name='etfhextractor_markets__demobarsts')
    op.drop_table('etfhextractor_markets__demobarsts')
    # ### end Alembic commands ###
